theme: jekyll-theme-leap-day
title: Cannon Laboratory 
description: Welcome to the Cannon Laboratory at the USDA-ARS ! We are focused on understanding how plants sense and response to their environment. In particular, we are interested in understanding the signaling and cell communication strategies that plants use to respond to external stimuli. 
